item {
  id: 1
  name: 'number_0'
}

item {
  id: 2
  name: 'number_1'
}

item {
  id: 3
  name: 'number_2'
}

item {
  id: 4
  name: 'number_3'
}

item {
  id: 5
  name: 'number_4'
}

item {
  id: 6
  name: 'number_5'
}

item {
  id: 7
  name: 'number_6'
}

item {
  id: 8
  name: 'number_7'
}

item {
  id: 9
  name: 'number_8'
}

item {
  id: 10
  name: 'number_9'
}
